config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sagas
  root "home#index"
  
  resources :feverdecorators
  root to: "home#index"
  
  resources :medicalprofiles
  resources :profiles
  devise_for :users
  
  
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  get '/infants' => 'infants#infantdoseofparacetamol'
  
  
  
  
  get '/dose', :controller=>'infants', :action=>'dose'
  
  post '/dose', :controller=>'infants', :action=>'dose'
  
  
  
  
  resources :profiles do
     
         resources :sagas
  end
  
  
   get '/yoga' => 'yogas#Input'
   
   get  '/validate' => 'yogas#Output'
   post '/validate' => 'yogas#Output'
   
   
   
   get  '/composite' => 'yogas#Composite'
   post '/composite' => 'yogas#Composite'
   
   get '/immunization' => 'immunizations#Input'
   get '/immunization' => 'immunizations#Output'
   post '/immunization' => 'immunizations#Output'
   

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  
  has_many :sagas
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_filter :authenticate_user!
  
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
def new
@profile = Profile.new
@profile.user_id = current_user.id
respond_to do |format|
format.html # new.html.erb
format.json { render json: @profile }
end
end
  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  
  def signedinuserprofile
      profile = Profile.find_by_user_id(current_user.id)
      if profile.nil?
         redirect_to "/profiles/new"
      else
        @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/profiles/#{@profile.id}"
      end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :Gender, :DateOfBirth, :BloodGroup, :RhFactor, :Height, :Weight, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :Gender %>
    <%= f.text_field :Gender %>
  </div>

  <div class="field">
    <%= f.label :DateOfBirth %>
    <%= f.text_field :DateOfBirth %>
  </div>

  <div class="field">
    <%= f.label :BloodGroup %>
    <%= f.text_field :BloodGroup %>
  </div>

  <div class="field">
    <%= f.label :RhFactor %>
    <%= f.text_field :RhFactor %>
  </div>

  <div class="field">
    <%= f.label :Height %>
    <%= f.text_field :Height %>
  </div>

  <div class="field">
    <%= f.label :Weight %>
    <%= f.text_field :Weight %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles Index</h1>


<%= link_to 'Back To Profile' , user_session_path  %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.Gender %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @profile.DateOfBirth %>
</p>

<p>
  <strong>Bloodgroup:</strong>
  <%= @profile.BloodGroup %>
</p>

<p>
  <strong>Rhfactor:</strong>
  <%= @profile.RhFactor %>
</p>

<p>
  <strong>Height:</strong>
  <%= @profile.Height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @profile.Weight %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> ||
<%= link_to 'Back', profiles_path( @profile) %>||

 <%= link_to 'Clinical Sagas' , profile_sagas_path(@profile) %> ||

 <%= link_to 'Fever Diagonistic Quick Guide' , feverdecorators_path %>||
 
 <%= link_to 'Infants Section' , infants_path %> ||
 
 <%= link_to 'Yoga'  , yoga_path %> ||
 
 <%= link_to 'Immunization Status' , immunization_path %>
 
 




    