config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sagas
  root "home#index"
  
  resources :feverdecorators
  root to: "home#index"
  
  resources :medicalprofiles
  resources :profiles
  devise_for :users
  
  
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  get '/infants' => 'infants#infantdoseofparacetamol'
  
  
  
  
  get '/dose', :controller=>'infants', :action=>'dose'
  
  post '/dose', :controller=>'infants', :action=>'dose'
  
  
  
  
  resources :profiles do
     
         resources :sagas
  end
  
  
   get '/yoga' => 'yogas#Input'
   
   get  '/validate' => 'yogas#Output'
   post '/validate' => 'yogas#Output'
   
   
   
   get  '/composite' => 'yogas#Composite'
   post '/composite' => 'yogas#Composite'
   
   get '/immunization' => 'immunizations#Input'
   get '/immunization' => 'immunizations#Output'
   post '/immunization' => 'immunizations#Output'
   

end

app/models/feverdecorator.rb
class Feverdecorator < ApplicationRecord
end

app/controllers/feverdecorators_controller.rb
require 'fever_decorator'



class FeverdecoratorsController < ApplicationController
  before_action :set_feverdecorator, only: [:show, :edit, :update, :destroy]

  # GET /feverdecorators
  # GET /feverdecorators.json
  def index
    @feverdecorators = Feverdecorator.all
  end

  # GET /feverdecorators/1
  # GET /feverdecorators/1.json
  def show
  end

  # GET /feverdecorators/new
  def new
    @feverdecorator = Feverdecorator.new
  end

  # GET /feverdecorators/1/edit
  def edit
  end

  # POST /feverdecorators
  # POST /feverdecorators.json
  
def create

      @feverdecorator = Feverdecorator.new()
      @feverdecorator.name = params[:feverdecorator][:name]
      @feverdecorator.temperature = params[:feverdecorator][:temperature]

      oFever = BasicFever.new(500, @feverdecorator.temperature)
      # add the extra features to fever
      
      if params[:feverdecorator][:continiousfever].to_s.length > 0 then
      oFever = ContinuousFever.new(oFever)
      end
      
      
      if params[:feverdecorator][:remittentfever].to_s.length > 0 then
      oFever = RemittentFever.new(oFever)
      end


      if params[:feverdecorator][:intermittentfever].to_s.length > 0 then
      oFever = IntermittentFever.new(oFever)
      end
      
      if params[:feverdecorator][:septicfever].to_s.length > 0 then
      oFever = SepticFever.new(oFever)
      end
      
      if params[:feverdecorator][:pelebsteinfever].to_s.length > 0 then
      oFever = PelEbsteinFever.new(oFever)
      end
      
      if params[:feverdecorator][:lowgradefever].to_s.length > 0 then
      oFever = LowGradeFever.new(oFever)
      end
      
      if params[:feverdecorator][:ladderfever].to_s.length > 0 then
      oFever = LadderFever.new(oFever)
      end
      
      if params[:feverdecorator][:relapsingfever].to_s.length > 0 then
         oFever = RelapsingFever.new(oFever)
      end
      
      if params[:feverdecorator][:tertianfever].to_s.length > 0 then
          oFever = TertianFever.new(oFever)
      end

      if params[:feverdecorator][:inversefever].to_s.length > 0 then
         oFever = InverseFever.new(oFever)
      end

      if params[:feverdecorator][:nightsweatfever].to_s.length > 0 then
         oFever = NightSweatFever.new(oFever)
      end
      
      if params[:feverdecorator][:rashfever].to_s.length > 0 then
         oFever = RashFever.new(oFever)
      end
      
      if params[:feverdecorator][:throatpainfever].to_s.length > 0 then
         oFever = ThroatPainFever.new(oFever)
      end
      
      if params[:feverdecorator][:HyperPyrexiaFever].to_s.length > 0 then
         oFever = HyperPyrexiaFever.new(oFever)
      end

      ## populate the description and fees field
      
      @feverdecorator.description = oFever.details
      @feverdecorator.fees = oFever.fees
      
      respond_to do |format|
      if @feverdecorator.save
            format.html { redirect_to @feverdecorator, notice: 'Diagonistic was successfully created.'}
            format.json { render :show, status: :created, location: @feverdecorator }
            else
            format.html { render :new }
            format.json { render json: @feverdecorator.errors, status: :unprocessable_entity }
      end
            end
end

  # PATCH/PUT /feverdecorators/1
  # PATCH/PUT /feverdecorators/1.json
  def update
    respond_to do |format|
      if @feverdecorator.update(feverdecorator_params)
        format.html { redirect_to @feverdecorator, notice: 'Feverdecorator was successfully updated.' }
        format.json { render :show, status: :ok, location: @feverdecorator }
      else
        format.html { render :edit }
        format.json { render json: @feverdecorator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feverdecorators/1
  # DELETE /feverdecorators/1.json
  def destroy
    @feverdecorator.destroy
    respond_to do |format|
      format.html { redirect_to feverdecorators_url, notice: 'Feverdecorator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feverdecorator
      @feverdecorator = Feverdecorator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feverdecorator_params
      params.require(:feverdecorator).permit(:name, :temperature, :description, :fees)
    end
end

app/helpers/feverdecorators_helper.rb
module FeverdecoratorsHelper
end

app/views/feverdecorators/_form.html.erb
<%= form_for(feverdecorator) do |f| %>
  <% if feverdecorator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feverdecorator.errors.count, "error") %> prohibited this feverdecorator from being saved:</h2>

      <ul>
      <% feverdecorator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :temperature %>
    <%= f.text_field :temperature %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :CostOfTreatment %>
    <%= f.text_field :fees %>
  </div>
  
  <div class="field">
   Temperature does not fluctuate more than 1 degree Celsius in 24 hours:
   <%= check_box_tag 'feverdecorator[continiousfever]', 'continiousfever' %>
  </div>
  
  <div class="field">
  Fever Fluctuates more than 2 degree Celsius in 24 hours:
  <%= check_box_tag 'feverdecorator[remittentfever]', 'remittentfever' %>
  </div>
  
  <div class="field">
  Fever is present for some hours in a day and remains to normal for the remaining hours:
  <%= check_box_tag 'feverdecorator[intermittentfever]', 'intermittentfever' %>
  </div>
  
  <div class="field">
  Temperature(Fever) variation is very formidable and exceeds 5 degree Celsius with Cuts in body :
  <%= check_box_tag 'feverdecorator[septicfever]', 'septicfever' %>
  </div>
  
  <div class="field">
  Temperature variation is very large and exceeds 5 degree Celsius:
  <%= check_box_tag 'feverdecorator[pelebsteinfever]', 'pelebsteinfever' %>
  </div>
  
  <div class="field">
  temperature present in evening only but doesnot exceed 100F with cough:
  <%= check_box_tag 'feverdecorator[lowgradefever]', 'lowgradefever' %>
  </div>
  
  <div class="field">
  Temperature(Fever) continiously inscreasing over a period of time with no indication of Remmission:
  <%= check_box_tag 'feverdecorator[ladderfever]', 'ladderfever' %>
  </div>
  
  <div class="field">
  Relapsing of fever after a certain interval:
  <%= check_box_tag 'feverdecorator[relapsingfever]', 'relapsingfever' %>
  </div>
  
  <div class="field">
  Fever occurs once in 3 days:
  <%= check_box_tag 'feverdecorator[tertianfever]', 'tertianfever' %>
  </div>
  
  <div class="field">
  Fever proliferates in morning rather than evening:
  <%= check_box_tag 'feverdecorator[inversefever]', 'inversefever' %>
  </div>
  
  <div class="field">
  Fever With sweat at night:
  <%= check_box_tag 'feverdecorator[nightsweatfever]', 'nightsweatfever' %>
  </div>
  
  <div class="field">
  Fever With Rash on Skin:
  <%= check_box_tag 'feverdecorator[rashfever]', 'rashfever' %>
  </div>
  
  <div class="field">
  Fever With Pain in throat:
  <%= check_box_tag 'feverdecorator[throatpainfever]', 'throatpainfever' %>
  </div>
  
  
  <div class="field">
  Fever With Temperature more than 105 degrees:
  <%= check_box_tag 'feverdecorator[HyperPyrexiaFever]', 'HyperPyrexiaFever' %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feverdecorators/edit.html.erb
<h1>Editing Feverdecorator</h1>

<%= render 'form', feverdecorator: @feverdecorator %>

<%= link_to 'Show', @feverdecorator %> |
<%= link_to 'Back', feverdecorators_path %>

app/views/feverdecorators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feverdecorators</h1>


<% if current_user.admin? %>




<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Temperature</th>
      <th>Description</th>
      <th>CostOfTreatment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feverdecorators.each do |feverdecorator| %>
      <tr>
        <td><%= feverdecorator.name %></td>
        <td><%= feverdecorator.temperature %></td>
        <td><%= feverdecorator.description %></td>
        <td><%= feverdecorator.fees %></td>
        <td><%= link_to 'Show', feverdecorator %></td>
        <td><%= link_to 'Edit', edit_feverdecorator_path(feverdecorator) %></td>
        <td><%= link_to 'Destroy', feverdecorator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end %>

<%= link_to 'New Feverdecorator', new_feverdecorator_path %>

app/views/feverdecorators/new.html.erb
<h1>New Feverdecorator</h1>

<%= render 'form', feverdecorator: @feverdecorator %>

<%= link_to 'Back', feverdecorators_path %>

app/views/feverdecorators/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @feverdecorator.name %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @feverdecorator.temperature %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feverdecorator.description %>
</p>

<p>
  <strong>CostOfTreatment:</strong>
  <%= @feverdecorator.fees %>
</p>

<%= link_to 'Edit', edit_feverdecorator_path(@feverdecorator) %> |
<%= link_to 'Back', feverdecorators_path %>