config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sagas
  root "home#index"
  
  resources :feverdecorators
  root to: "home#index"
  
  resources :medicalprofiles
  resources :profiles
  devise_for :users
  
  
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  get '/infants' => 'infants#infantdoseofparacetamol'
  
  
  
  
  get '/dose', :controller=>'infants', :action=>'dose'
  
  post '/dose', :controller=>'infants', :action=>'dose'
  
  
  
  
  resources :profiles do
     
         resources :sagas
  end
  
  
   get '/yoga' => 'yogas#Input'
   
   get  '/validate' => 'yogas#Output'
   post '/validate' => 'yogas#Output'
   
   
   
   get  '/composite' => 'yogas#Composite'
   post '/composite' => 'yogas#Composite'
   
   get '/immunization' => 'immunizations#Input'
   get '/immunization' => 'immunizations#Output'
   post '/immunization' => 'immunizations#Output'
   

end

app/helpers/medicalprofiles_helper.rb
module MedicalprofilesHelper
end

app/views/medicalprofiles/_form.html.erb
<%= form_for(medicalprofile) do |f| %>
  <% if medicalprofile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicalprofile.errors.count, "error") %> prohibited this medicalprofile from being saved:</h2>

      <ul>
      <% medicalprofile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ImmunizationStatus %>
    <%= f.text_field :ImmunizationStatus %>
  </div>

  <div class="field">
    <%= f.label :Surgeries %>
    <%= f.text_field :Surgeries %>
  </div>

  <div class="field">
    <%= f.label :UnderlyingMedicalIllness %>
    <%= f.text_field :UnderlyingMedicalIllness %>
  </div>

  <div class="field">
    <%= f.label :Allergies %>
    <%= f.text_field :Allergies %>
  </div>

  <div class="field">
    <%= f.label :SexuallyTransmittedDiseases %>
    <%= f.text_field :SexuallyTransmittedDiseases %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicalprofiles/edit.html.erb
<h1>Editing Medicalprofile</h1>

<%= render 'form', medicalprofile: @medicalprofile %>

<%= link_to 'Show', @medicalprofile %> |
<%= link_to 'Back', medicalprofiles_path %>

app/views/medicalprofiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicalprofiles</h1>

<head>
<style>

table {
    border-collapse: collapse;
}

table, th, td {
    border: 1px solid black;
}

th, td {
    padding: 5px;
}


th {
    text-align: left;
}

</style>
</head>




<table>
  <thead>
    <tr>
      <th>Immunizationstatus</th>
      <th>Surgeries</th>
      <th>Underlyingmedicalillness</th>
      <th>Allergies</th>
      <th>Sexuallytransmitteddiseases</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicalprofiles.each do |medicalprofile| %>
      <tr>
        <td><%= medicalprofile.ImmunizationStatus %></td>
        <td><%= medicalprofile.Surgeries %></td>
        <td><%= medicalprofile.UnderlyingMedicalIllness %></td>
        <td><%= medicalprofile.Allergies %></td>
        <td><%= medicalprofile.SexuallyTransmittedDiseases %></td>
        <td><%= medicalprofile.user %></td>
        <td><%= link_to 'Show', medicalprofile %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_medicalprofile_path(medicalprofile) %></td>
        <td><%= link_to 'Destroy', medicalprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New Medicalprofile', new_medicalprofile_path %> ||  <%= link_to 'Profile' , profiles_path%>




                             

app/views/medicalprofiles/new.html.erb
<h1>New Medicalprofile</h1>

<%= render 'form', medicalprofile: @medicalprofile %>

<%= link_to 'Back', medicalprofiles_path %>

app/views/medicalprofiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Immunizationstatus:</strong>
  <%= @medicalprofile.ImmunizationStatus %>
</p>

<p>
  <strong>Surgeries:</strong>
  <%= @medicalprofile.Surgeries %>
</p>

<p>
  <strong>Underlyingmedicalillness:</strong>
  <%= @medicalprofile.UnderlyingMedicalIllness %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @medicalprofile.Allergies %>
</p>

<p>
  <strong>Sexuallytransmitteddiseases:</strong>
  <%= @medicalprofile.SexuallyTransmittedDiseases %>
</p>

<p>
  <strong>User:</strong>
  <%= @medicalprofile.user %>
</p>

<%= link_to 'Edit', edit_medicalprofile_path(@medicalprofile) %> |
<%= link_to 'Back', medicalprofiles_path %>