config/routes.rb
Rails.application.routes.draw do
  
  
  resources :sagas
  root "home#index"
  
  resources :feverdecorators
  root to: "home#index"
  
  resources :medicalprofiles
  resources :profiles
  devise_for :users
  
  
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  get '/infants' => 'infants#infantdoseofparacetamol'
  
  
  
  
  get '/dose', :controller=>'infants', :action=>'dose'
  
  post '/dose', :controller=>'infants', :action=>'dose'
  
  
  
  
  resources :profiles do
     
         resources :sagas
  end
  
  
   get '/yoga' => 'yogas#Input'
   
   get  '/validate' => 'yogas#Output'
   post '/validate' => 'yogas#Output'
   
   
   
   get  '/composite' => 'yogas#Composite'
   post '/composite' => 'yogas#Composite'
   
   get '/immunization' => 'immunizations#Input'
   get '/immunization' => 'immunizations#Output'
   post '/immunization' => 'immunizations#Output'
   

end

app/models/saga.rb
class Saga < ApplicationRecord
  belongs_to :profile
end

app/controllers/sagas_controller.rb
class SagasController < ApplicationController
  before_action :set_saga, only: [:show, :edit, :update, :destroy]

 # GET /sagas
 # GET /sagas.json
  def index
    @profile = Profile.find(params[:profile_id])
    @sagas = @profile.sagas
  end

  # GET /sagas/1
  # GET /sagas/1.json
  def show
    
      @profile = Profile.find(params[:profile_id])
      @saga = @profile.sagas.find(params[:id])
 
  end

    # GET /sagas/new
  def new
    
    @profile = Profile.find(params[:profile_id])
    @saga = @profile.sagas.build
  end

  # GET /sagas/1/edit
  def edit
    
    @profile = Profile.find(params[:profile_id])
    @saga = @profile.sagas.find(params[:id])
  end

  # POST /sagas
  # POST /sagas.json
  def create
    @profile = Profile.find(params[:profile_id])
    
    
    @saga = @profile.sagas.build(saga_params)
    
  if @saga.save
# Save the saga successfully
      redirect_to profile_saga_url(@profile ,  @saga)
   else
      render :action => "new"
  end
  end

  # PATCH/PUT /sagas/1
  # PATCH/PUT /sagas/1.json
  def update

    @profile = Profile.find(params[:profile_id])
    @saga = Saga.find(params[:id])
	
    if @saga.update_attributes(saga_params)
       # Save the review successfully
       redirect_to profile_saga_url(@profile, @saga)
    else
       render :action => "edit"
    end
  end

  # DELETE /sagas/1
  # DELETE /sagas/1.json
def destroy
   @profile = Profile.find(params[:profile_id])
   @saga = Saga.find(params[:id])
    
   @saga.destroy
   respond_to do |format|
   format.html { redirect_to profile_sagas_url }
   format.xml { head :ok }
   end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saga
      @saga = Saga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saga_params
      params.require(:saga).permit(:ImmunizationStatus, :Surgeries, :UnderlyingMedicalIllness, :Allergies, :SexuallyTransmittedDiseases)
    end
end

app/helpers/sagas_helper.rb
module SagasHelper
end

app/views/sagas/_form.html.erb
<%= form_for([@profile , @saga]) do |f| %>
  <% if @saga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saga.errors.count, "error") %> prohibited this saga from being saved:</h2>

      <ul>
      <% @saga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ImmunizationStatus %>
    <%= f.text_field :ImmunizationStatus %>
  </div>

  <div class="field">
    <%= f.label :Surgeries %>
    <%= f.text_field :Surgeries %>
  </div>

  <div class="field">
    <%= f.label :UnderlyingMedicalIllness %>
    <%= f.text_field :UnderlyingMedicalIllness %>
  </div>

  <div class="field">
    <%= f.label :Allergies %>
    <%= f.text_field :Allergies %>
  </div>

  <div class="field">
    <%= f.label :SexuallyTransmittedDiseases %>
    <%= f.text_field :SexuallyTransmittedDiseases %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sagas/edit.html.erb
<h1>Editing Saga</h1>

<%= render 'form', saga: @saga %>

<%= link_to 'Show', @saga %> |
<%= link_to 'Back', sagas_path %>

app/views/sagas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clinical History</h1> 

<head>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}


th {
    background-color: black;
    color: white;
}

h1 {
    background-color: lightgrey;
    width: 300px;
    border: 25px solid black;
    padding: 25px;
    margin: 25px;

}





</style>
</head>



<body>

<table>
  <thead>
    <tr>
      <th>Immunization Status</th>
      <th>Surgeries</th>
      <th>Underlying Medical Illness</th>
      <th>Allergies</th>
      <th>Sexually Transmitted Diseases</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sagas.each do |saga| %>
      <tr>
        <td><%= saga.ImmunizationStatus %></td>
        <td><%= saga.Surgeries %></td>
        <td><%= saga.UnderlyingMedicalIllness %></td>
        <td><%= saga.Allergies %></td>
        <td><%= saga.SexuallyTransmittedDiseases %></td>

        <td><%= link_to 'Show', profile_saga_path(@profile , saga) %></td>
        <td><%= link_to 'Edit', edit_profile_saga_path(@profile ,saga) %></td>
        <td><%= link_to 'Destroy', profile_saga_path(@profile, saga), data: { confirm: 'Are you sure?' } ,method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</body>

<br>

<%= link_to 'New Saga', new_profile_saga_path(@profile) %>

app/views/sagas/new.html.erb
<h1>New Saga</h1>

<%= render 'form', saga: @saga %>

<%= link_to 'Back', sagas_path %>

app/views/sagas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Immunizationstatus:</strong>
  <%= @saga.ImmunizationStatus %>
</p>

<p>
  <strong>Surgeries:</strong>
  <%= @saga.Surgeries %>
</p>

<p>
  <strong>Underlyingmedicalillness:</strong>
  <%= @saga.UnderlyingMedicalIllness %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @saga.Allergies %>
</p>

<p>
  <strong>Sexuallytransmitteddiseases:</strong>
  <%= @saga.SexuallyTransmittedDiseases %>
</p>


<%= link_to 'Edit', edit_profile_saga_path(@profile, @saga) %> |
<%= link_to 'Back', profile_sagas_path(@profile) %>